# Generated by Django 2.0.4 on 2020-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clpeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clr_name', models.CharField(db_column='clr_name', max_length=20, verbose_name='执行者')),
                ('cylx', models.CharField(db_column='cylx', max_length=20, verbose_name='处理的创意类型')),
            ],
            options={
                'db_table': 'clpeople',
            },
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='名字')),
                ('sqm', models.CharField(db_column='sqm', max_length=20, verbose_name='邮箱授权码')),
            ],
            options={
                'db_table': 'man',
            },
        ),
    ]
